USE scss_punny_db;

CREATE TABLE IF NOT EXISTS puns (
    pun_id INT AUTO_INCREMENT,
    pun TEXT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    lastupdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(pun_id)
);
